default:
  navigation:
    - title: Accesorios
      subtitle: Categorias
      url: /t/accesorios
      items:
        - :title: Aros
          :url: /t/accesorios/aros
        - :title: Collares
          :url: /t/accesorios/collares
        - :title: Tobilleras
          :url: /t/accesorios/tobilleras
        - :title: Anillos
          :url: /t/accesorios/anillos
        - :title: Pulseras
          :url: /t/accesorios/pulseras
        - :title: Tocados
          :url: /t/accesorios/tocados
      promo_banners:
        - subtitle: Nueva colección
          title: Edén
          url: /t/nuevo
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Ofertas especiales
          title: Promoción Accesorios
          url: /t/promocion_accesorios
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Casual
      subtitle: Categorias
      url: /t/Casual
      items:
        - :title: Poleras
          :url: /t/casual/poleras
        - :title: Blusas
          :url: /t/casual/blusas
        - :title: Sweaters
          :url: /t/casual/sweaters
        - :title: Shorts
          :url: /t/casual/shorts
        - :title: Faldas
          :url: /t/casual/faldas
        - :title: Abrigos
          :url: /t/casual/abrigos
        - :title: Pantalones
          :url: /t/casual/pantalones
      promo_banners:
        - subtitle: Nueva colección
          title: Verano
          url: /t/nuevo
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Ofertas especiales
          title: Promoción Ropa
          url: /t/promocion_ropa
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Formal
      subtitle: Categorias
      url: /t/Formal
      items:
        - :title: Faldas
          :url: /t/formal/faldas
        - :title: Pantalones
          :url: /t/formal/pantalones
        - :title: Vestidos
          :url: /t/formal/vestidos
      promo_banners:
        - subtitle: Nueva colección
          title: Verano
          url: /t/nuevo
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Ofertas especiales
          title: Promoción Ropa
          url: /t/promocion_ropa
          image: 'meganav/promo_banner_right-third-category.jpg'
